#!/usr/bin/env bash
# Configures etc/hosts
LOCAL_HOST="127.0.0.1	localhost";
FACEBOOK="8.8.8.8	facebook";
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
