#!/usr/bin/env bash
# create a key pair
# Define variables
KEY_NAME="school"      # Change this to the desired key name
PASSPHRASE="betty"    # Change this to your desired passphrase

# Generate the SSH key pair without manual input
ssh-keygen -b 4096 -t rsa -f "$KEY_NAME" -N "$PASSPHRASE"
